name: Pull Request
on:
  pull_request:
    types: [opened, labeled, synchronize, reopened]
jobs:
  RunTests:
    runs-on: ubuntu-latest
    steps:
      # Setup
      - uses: actions/checkout@v2
      # ruby/setup-ruby@v1 will use .ruby-version
      - uses: ruby/setup-ruby@v1
        with:
          bundler-cache: true
      # Test
      - name: Test with rspec
        run: bundle exec rspec
      - name: Run Rubocop
        run: bundle exec rubocop
