name: Ruby

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up Ruby 3.0.3
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: 3.0.3
        bundler-cache: true
    - name: Run RSpec
      run: bundle exec rspec
    - name: Run Rubocop
      run: bundle exec rubocop
